-- =========================================
-- RETAIL SALES & INVENTORY ANALYTICS PROJECT
-- =========================================


-- =========================================
-- CREATE DATABASE
-- =========================================

CREATE DATABASE retail_project;

USE retail_project;


-- =========================================
-- CHECK CUSTOMER TABLE DATA
-- Display first 5 records from customers table
-- =========================================

SELECT * 
FROM customers 
LIMIT 5;


-- =========================================
-- CHECK ORDERS TABLE DATA
-- Display first 5 records from orders table
-- =========================================

SELECT * 
FROM orders 
LIMIT 5;


-- =========================================
-- CHECK PRODUCTS TABLE DATA
-- Display first 5 records from products table
-- =========================================

SELECT * 
FROM products 
LIMIT 5;


-- =========================================
-- TOTAL SALES ANALYSIS
-- Calculate total revenue generated
-- =========================================

SELECT 
SUM(list_price * quantity) AS total_sales
FROM order_items;


-- =========================================
-- TOTAL ORDERS ANALYSIS
-- Count total number of customer orders
-- =========================================

SELECT 
COUNT(*) AS total_orders
FROM orders;


-- =========================================
-- TOP SELLING PRODUCTS
-- Find products with highest sales quantity
-- =========================================

SELECT 
product_id,
SUM(quantity) AS total_sold
FROM order_items
GROUP BY product_id
ORDER BY total_sold DESC;


-- =========================================
-- STORE-WISE SALES ANALYSIS
-- Calculate sales generated by each store
-- =========================================

SELECT 
s.store_name,
SUM(oi.list_price * oi.quantity) AS sales
FROM orders o
JOIN order_items oi 
ON o.order_id = oi.order_id
JOIN stores s
ON o.store_id = s.store_id
GROUP BY s.store_name;


-- =========================================
-- STAFF PERFORMANCE ANALYSIS
-- Count orders handled by each staff member
-- =========================================

SELECT 
st.staff_id,
st.first_name,
st.last_name,
COUNT(o.order_id) AS total_orders
FROM staffs st
JOIN orders o
ON st.staff_id = o.staff_id
GROUP BY st.staff_id, st.first_name, st.last_name;


-- =========================================
-- CATEGORY-WISE SALES ANALYSIS
-- Calculate revenue generated by each category
-- =========================================

SELECT 
c.category_name,
SUM(oi.list_price * oi.quantity) AS revenue
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
JOIN categories c
ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY revenue DESC;


-- =========================================
-- BRAND-WISE SALES ANALYSIS
-- Find top performing brands by sales
-- =========================================

SELECT 
b.brand_name,
SUM(oi.list_price * oi.quantity) AS total_sales
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
JOIN brands b
ON p.brand_id = b.brand_id
GROUP BY b.brand_name
ORDER BY total_sales DESC;


-- =========================================
-- MONTHLY SALES TREND ANALYSIS
-- Analyze monthly revenue growth
-- =========================================

SELECT 
MONTH(order_date) AS month,
SUM(oi.list_price * oi.quantity) AS revenue
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY MONTH(order_date)
ORDER BY month;


-- =========================================
-- CUSTOMER ORDER ANALYSIS
-- Find customers with highest orders
-- =========================================

SELECT 
c.customer_id,
c.first_name,
c.last_name,
COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_orders DESC;


-- =========================================
-- INVENTORY STOCK ANALYSIS
-- Check available stock for each product
-- =========================================

SELECT 
p.product_name,
SUM(s.quantity) AS stock_left
FROM stocks s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.product_name
ORDER BY stock_left DESC;


-- =========================================
-- STORE-WISE ORDER COUNT
-- Count total orders from each store
-- =========================================

SELECT 
s.store_name,
COUNT(o.order_id) AS total_orders
FROM stores s
JOIN orders o
ON s.store_id = o.store_id
GROUP BY s.store_name
ORDER BY total_orders DESC;


-- =========================================
-- AVERAGE SALES VALUE ANALYSIS
-- Calculate average sales amount per order item
-- =========================================

SELECT 
AVG(list_price * quantity) AS average_sales
FROM order_items;


-- =========================================
-- MAXIMUM PRODUCT PRICE ANALYSIS
-- Find highest priced product
-- =========================================

SELECT 
product_name,
list_price
FROM products
ORDER BY list_price DESC
LIMIT 1;


-- =========================================
-- MINIMUM PRODUCT PRICE ANALYSIS
-- Find lowest priced product
-- =========================================

SELECT 
product_name,
list_price
FROM products
ORDER BY list_price ASC
LIMIT 1;


-- =========================================
-- TOTAL CUSTOMERS ANALYSIS
-- Count total customers in database
-- =========================================

SELECT 
COUNT(*) AS total_customers
FROM customers;


-- =========================================
-- TOTAL PRODUCTS ANALYSIS
-- Count total products available
-- =========================================

SELECT 
COUNT(*) AS total_products
FROM products;


-- =========================================
-- TOTAL STAFF ANALYSIS
-- Count total staff members
-- =========================================

SELECT 
COUNT(*) AS total_staff
FROM staffs;


-- =========================================
-- ORDER STATUS ANALYSIS
-- Analyze different order statuses
-- =========================================

SELECT 
order_status,
COUNT(*) AS total_status
FROM orders
GROUP BY order_status;


-- =========================================
-- TOP 5 PRODUCTS BY SALES
-- Display top 5 best selling products
-- =========================================

SELECT 
p.product_name,
SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_sold DESC
LIMIT 5;


-- =========================================
-- LOW STOCK PRODUCTS ANALYSIS
-- Find products with low inventory stock
-- =========================================

SELECT 
p.product_name,
SUM(s.quantity) AS stock_quantity
FROM stocks s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.product_name
HAVING stock_quantity < 10
ORDER BY stock_quantity ASC;